name: Playwright Tests

on:
  push:
    branches: [playwright-auto]
  pull_request:
    branches: [playwright-auto]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'   # 🔥 thêm cache cho nhanh

      - name: Install dependencies
        run: npm ci   # 🔥 tốt hơn npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # - run: ls -R
      - name: Print test titles
        run: npx playwright test --list

      - name: Run Tests
        # run: npx playwright test TESTS/login.descr.spec.ts
        run: npx playwright test TESTS/example.spec.ts

      - name: Upload HTML Report
        if: always()   # 🔥 rất quan trọng
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/